name:
title: Michael Maldonado
description: A strategic project and product manager that is detail-oriented, obsessed with data, driven by results, and consumed by metrics. I have over 6 years of experience and a deep passion for software, project management, analytics and design.
# email: michael@maldo.co
# url: "http://maldo.co"
# twitter_username: todo
# github_username:  todo

# Build settings
sass:
  sass_dir: _sass
  style: compressed
  sourcemap: inline
  # debug_info: true
  line_numbers: true
  line_comments: true
plugins:
  - jekyll-feed